/**
 * generated by Xtext 2.18.0.M3
 */
package org.omg.sysml.xtext.ui.quickfix;

import java.util.Collections;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class SysMLQuickfixProvider extends DefaultQuickfixProvider {
  @Override
  public Iterable<IEObjectDescription> queryScope(final IScope scope) {
    return Collections.<IEObjectDescription>emptySet();
  }
}
