/**
 * generated by Xtext 2.18.0.M3
 */
package org.omg.sysml.xtext.ui;

import com.google.inject.Provider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.shared.Access;
import org.omg.kerml.xtext.ui.KerMLAntlrTokenToAttributeIdMapper;
import org.omg.kerml.xtext.ui.KerMLHighlightingConfiguration;
import org.omg.kerml.xtext.ui.KerMLUserKeywordHighlightingCalculator;
import org.omg.sysml.xtext.ui.quickfix.SysMLQuickfixProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SysMLUiModule extends AbstractSysMLUiModule {
  @Override
  public Class<? extends IssueResolutionProvider> bindIssueResolutionProvider() {
    return SysMLQuickfixProvider.class;
  }

  public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
    return KerMLUserKeywordHighlightingCalculator.class;
  }

  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return KerMLHighlightingConfiguration.class;
  }

  public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    return KerMLAntlrTokenToAttributeIdMapper.class;
  }

  @Override
  public Provider<? extends IAllContainersState> provideIAllContainersState() {
    return Access.getWorkspaceProjectsState();
  }

  public SysMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
